version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongo_dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    container_name: redis_dev
    ports:
      - "6379:6379"

volumes:
  mongo-data:
