version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres_dev
    restart: always
    environment:
      POSTGRES_USER: autodb_user
      POSTGRES_PASSWORD: autodb_pass
      POSTGRES_DB: autodb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server/src/migrations:/migrations

  redis:
    image: redis
    container_name: redis_dev
    ports:
      - "6379:6379"

volumes:
  postgres-data:
